apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: collector
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
        iam.gke.io/gcp-service-account: otel-collector@careful-striker-429807-p1.iam.gserviceaccount.com
      labels:
        io.kompose.service: collector
    spec:
      serviceAccountName: otel-collector-ksa
      containers:
        - args:
            - --config=/etc/otelcol-contrib/otel-collector.yml
          image: asia-east1-docker.pkg.dev/careful-striker-429807-p1/open/otel/opentelemetry-collector-contrib:0.91.0
          name: collector
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/otelcol-contrib/otel-collector.yml
              name: collector-cm0
              subPath: otel-collector.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: otel-collector.yml
                path: otel-collector.yml
            name: collector-cm0
          name: collector-cm0
