apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zipkin-all-in-one
  name: zipkin-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin-all-in-one
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: zipkin-all-in-one
    spec:
      containers:
        - image: openzipkin/zipkin:latest
          name: zipkin
          ports:
            - containerPort: 9411
              protocol: TCP
      restartPolicy: Always
